# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SMServer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMServer
  pod 'Telegraph'
  pod 'Criollo', '~> 1.0'

  # target 'SMServerTests' do
  #   inherit! :search_paths
    # Pods for testing
  # end

  # target 'SMServerUITests' do
    # Pods for testing
  # end

end
