# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'SMServer' do
  platform :ios, '13.0'
	
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMServer
  pod 'Telegraph'
  # I'm sorry that it's a local repo; this podspec is also available online for you to download:
  # https://raw.githubusercontent.com/iandwelker/Criollo/master/Criollo.podspec
  pod 'Criollo', :podspec => '/Users/ian/Documents/Coding/foss/Criollo/Criollo.podspec'

end

target 'SMServer_Mac' do
  platform :osx, '10.13'

  use_frameworks!

  pod 'Telegraph'
  pod 'Criollo', :podspec => '/Users/ian/Documents/Coding/foss/Criollo/Criollo.podspec'

end
